// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCompany.Models;

#nullable disable

namespace MyCompany.Migrations
{
    [DbContext(typeof(MyCompanyContext))]
    [Migration("20250204150622_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyCompany.Models.Department", b =>
                {
                    b.Property<int>("Dnum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dnum"));

                    b.Property<string>("Dname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MGRSSN")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MGRStart_Date")
                        .HasColumnType("datetime")
                        .HasColumnName("MGRStart Date");

                    b.HasKey("Dnum");

                    b.HasIndex("MGRSSN")
                        .IsUnique()
                        .HasFilter("[MGRSSN] IS NOT NULL");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("MyCompany.Models.Employee", b =>
                {
                    b.Property<int>("SSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SSN"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Dno")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Passowrd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Salary")
                        .HasColumnType("int");

                    b.Property<int?>("Superssn")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SSN");

                    b.HasIndex("Dno");

                    b.HasIndex("Superssn");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("MyCompany.Models.Project", b =>
                {
                    b.Property<int>("PNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PNum"));

                    b.Property<int?>("Dnum")
                        .HasColumnType("int");

                    b.Property<string>("Plocation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PNum");

                    b.HasIndex("Dnum");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("MyCompany.Models.Works_For", b =>
                {
                    b.Property<int>("ESSn")
                        .HasColumnType("int");

                    b.Property<int>("Pno")
                        .HasColumnType("int");

                    b.HasKey("ESSn", "Pno");

                    b.HasIndex("Pno");

                    b.ToTable("Works_Fors");
                });

            modelBuilder.Entity("MyCompany.Models.Department", b =>
                {
                    b.HasOne("MyCompany.Models.Employee", "MGRSSNNavigation")
                        .WithOne("Departments")
                        .HasForeignKey("MyCompany.Models.Department", "MGRSSN");

                    b.Navigation("MGRSSNNavigation");
                });

            modelBuilder.Entity("MyCompany.Models.Employee", b =>
                {
                    b.HasOne("MyCompany.Models.Department", "DnoNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("Dno");

                    b.HasOne("MyCompany.Models.Employee", "SuperssnNavigation")
                        .WithMany("InverseSuperssnNavigation")
                        .HasForeignKey("Superssn");

                    b.Navigation("DnoNavigation");

                    b.Navigation("SuperssnNavigation");
                });

            modelBuilder.Entity("MyCompany.Models.Project", b =>
                {
                    b.HasOne("MyCompany.Models.Department", "DnumNavigation")
                        .WithMany("Projects")
                        .HasForeignKey("Dnum");

                    b.Navigation("DnumNavigation");
                });

            modelBuilder.Entity("MyCompany.Models.Works_For", b =>
                {
                    b.HasOne("MyCompany.Models.Employee", "ESSnNavigation")
                        .WithMany("Works_fors")
                        .HasForeignKey("ESSn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyCompany.Models.Project", "PnoNavigation")
                        .WithMany("Works_fors")
                        .HasForeignKey("Pno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ESSnNavigation");

                    b.Navigation("PnoNavigation");
                });

            modelBuilder.Entity("MyCompany.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("MyCompany.Models.Employee", b =>
                {
                    b.Navigation("Departments")
                        .IsRequired();

                    b.Navigation("InverseSuperssnNavigation");

                    b.Navigation("Works_fors");
                });

            modelBuilder.Entity("MyCompany.Models.Project", b =>
                {
                    b.Navigation("Works_fors");
                });
#pragma warning restore 612, 618
        }
    }
}
